---
title: "Untitled"
output: html_document
date: "2025-04-06"
editor_options: 
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(here)
source(here("source", "get_lib.R"))
```

# Gap Minder

```{r}
# ctrl +alt+i : insert code chunk
# ctrl +shift + c: comment out
#ctrl +shift + m  : insert pipe operator
#ctrl +enter : execute line
#ctrl+shift+k : knit
gap <- fread(here("data","gapminder.csv"))
#head(gap)

length(gap$year)
length(unique(gap$year))

my_ten <- unique(gap$country)[1:10]
```

##Selecting rows and columns
```{r}
gap %>% select(c("pop","year")) %>% head()

gap %>% filter(country == "Afghanistan") %>% head()

gap %>% filter(country %in% my_ten) %>% head()

# we can also define the vector of names first

```


##Plot
```{r fig.height=6, echo=FALSE}
gap %>% ggplot(aes(x=year, y=pop))+ geom_point()
```

###My ten
```{r fig.height=11}
gap %>% filter(country %in% my_ten) %>% ggplot(aes(x=year, y=pop, color = country))+ geom_point()+theme(legend.position = "top")
```

### sub plots
```{r}
p1<- gap %>%  filter(continent=="Asia"& gdpPercap >= 30000) %>% ggplot(aes(x=year, y=pop, color = country))+ geom_point()+theme(legend.position = "top")

p2<- gap %>%  filter(continent=="Asia"& gdpPercap >= 30000) %>% filter(pop<5000000) %>%  ggplot(aes(x=year, y=pop, color = country))+ geom_point()+theme(legend.position = "top")

p1|p2
```

##Summary
```{r}
# look at the continents we have
table(gap$continent)

dim(gap)

head(gap)

gap %>% filter(year == 1952) %>% group_by(country) %>% reframe(ave = sum(gdpPercap)) %>% ggplot(aes(x=country, y=ave))+geom_col() + coord_flip()


```
